project:
  type: website

website:
  title: "Sample Space"
  favicon: favicon.ico
  navbar:
    logo: "media/images/UCL-sample-space.png"
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "News, Views and Research<br>from the UCL Department of Statistical Science"
        href: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/stats_ucl
      - icon: instagram
        href: https://www.instagram.com/ucl.stats
      - icon: linkedin
        href: https://linkedin.com/in/statistical-science-ucl-906b9a201/
      - icon: facebook
        href: https://facebook.com/StatisticalScience
      - icon: github
        href: https://github.com/stats-ucl
      - icon: youtube
        href: https://www.youtube.com/c/uclstatisticalscienceseminars
      - icon: headphones
        href: https://soundcloud.com/uclsound/sets/sample-space
        aria-label: Soundcloud podcast
  page-footer: 
    left: "[Sample Space](index.html): News, Views and Research from the [UCL Department of Statistical Science](https://www.ucl.ac.uk/statistics/department-statistical-science)"
    right:
      - icon: twitter
        href: https://twitter.com/stats_ucl
      - icon: instagram
        href: https://www.instagram.com/ucl.stats
      - icon: linkedin
        href: https://linkedin.com/in/statistical-science-ucl-906b9a201/
      - icon: facebook
        href: https://facebook.com/StatisticalScience
      - icon: github
        href: https://github.com/stats-ucl
      - icon: youtube
        href: https://www.youtube.com/c/uclstatisticalscienceseminars
      - icon: headphones
        href: https://soundcloud.com/uclsound/sets/sample-space
        aria-label: Soundcloud podcast
        
sidebar:
  style: floating
  search: true
  location: left
  logo: "media/images/UCL-sample-space.png"

format:
  html:
    theme: sample_stats.scss
    css: styles.css
    page-layout: full
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet"/>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">


