---
title: ""
subtitle: ""
css: index-mods.css
listing: 
  - id: top-block
    categories: true
    contents: 
      - posts
    type: grid
    image-height: 300px
    sort: 
      - "categories desc"
      - "date desc"
    grid-columns: 3
    page-size: 9
    date-format: "medium"
    max-description-length: 300
    fields: [image,title,author,date,description,reading-time]

title-block-banner: false
---


## News, Views and Research from the UCL Department of Statistical Science

::::: {.column-screen-mod}

:::: {.grid}

::: {.g-col-7 .g-col-md-9}

:::: {.content-block}
::: {#top-block}
:::
::::

:::

::: {.g-col-5 .g-col-md-3}

<div style='margin-top:20px'>
<a class="twitter-timeline" data-width="100%" max-width="100%" data-height="1200" data-theme="light" href="https://twitter.com/stats_UCL?ref_src=twsrc%5Etfw">Tweets by stats_UCL</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
</div>

:::

::::

:::::



## A bit about us

The [UCL Department of Statistical Science](https://www.ucl.ac.uk/statistics/) was founded in 1911 as the Department of Applied Statistics.  It was the first university department of Statistics in the world --- you can read about our early history [here](https://www.ucl.ac.uk/statistics/our-early-history-1).

Today, the department hosts around 50 academic and lecturing staff, over 10 research staff, around 50 PhD students and is supported by over 10 professional staff members. We are a vibrant community, operating at the centre of the academic environment, due to our large network of scientific collaborations, within UCL and with external partners, both in academia and various industry.

We work in a [wide range of methodologies and applications](https://www.ucl.ac.uk/statistics/research), as well as in pedagogical activity. We organise a series of weekly [seminars](https://www.ucl.ac.uk/statistics/seminar), which, whenever possible, are also available remotely and through our own [YouTube Channel](https://www.youtube.com/c/uclstatisticalscienceseminars). We also run a podcast ([Random Talks](https://soundcloud.com/uclsound/sets/sample-space)). You can follow our updates also on [Twitter](https://twitter.com/stats_ucl), [Instagram](https://www.instagram.com/ucl.stats), [LinkedIn](https://linkedin.com/in/statistical-science-ucl-906b9a201/) and [Facebook](https://facebook.com/StatisticalScience). 