---
title: "Teaching ‘difficult knowledge’" 
date: 2023-07-05
categories:
  - "ELEP"
description:  |
   *Teaching ‘difficult knowledge’: UCL’s eugenics history and the implications for teaching and learning in Statistics.*
info:
  author: "Mrs Helen Knowler"
  pic: Knowler_Nov_22_Portrait.jpg
  bio: Mrs Helen Knowler is academic lead for the Eugenics Legacy Education Project (ELEP)
  website: https://www.ucl.ac.uk/teaching-learning/professional-development/eugenics-legacy-education-project-elep-0
---

The Eugenics Legacy Education Project (ELEP) at UCL began in September 2022 as a direct result of the [**UCL** **Eugenics Inquiry Response report**](https://www.ucl.ac.uk/teaching-learning/professional-development/eugenics-legacy-education-project-elep-0). The report recommended a programme of education activity be undertaken to explore the ways that teaching and learning practices at UCL can take account of the historical links to eugenics and to consider the implications for current and future educational activities. Confronting the harms of eugenics as an educational endeavor means critically reflecting on issues such as the role of curriculum development, planning staff support and learning, the use of high-quality resources for teaching historical and contemporary issues as well as opportunities develop productive pedagogies when teaching this ‘difficult knowledge’.

ELEP has five strands of activity designed to develop our collective educational capacity to include teaching about UCL’s eugenics legacy in contextually appropriate and discipline specific ways. We are keen to work with colleagues across disciplines at UCL and are particularly looking forward to collaborating with the Department of Statistical Science since there has been some important work taking place before ELEP was established. For example, [Professor Tom Fearn’s podcast](https://mediacentral.ucl.ac.uk/Play/71860#!) on the history of statistics and eugenics outlines the importance of a continuing engagement with the harms of the eugenics discourse and ways to address this in our educational activities. The process of [de-naming of rooms and buildings](https://www.ucl.ac.uk/statistics/our-early-history-1) associated with eugenicists and the plaque that marks this process is an important opportunity to think about the educational opportunities this creates for engagement with reparative educational futures. The continuing work on [inclusion and diversity](https://www.ucl.ac.uk/statistics/equality-diversity-inclusion-0) that is evident when talking to senior leadership in the department prompts questions around the relationship between strategies for developing and supporting the flourishing of diverse communities in the shadow of our eugenics history.

The Eugenics Inquiry Response Report acknowledged the complexity of developing teaching and learning activities that might confront and address eugenics legacies at UCL. Between 2022-2025 ELEP aims to:

- Develop a set of guidelines, staff resources, and learning opportunities that embed **visibility** and** awareness** of UCL’s history of eugenics in teaching and learning activities across the organisation.
- Support the ability of students, staff, and the wider community to **engage** with UCL’s eugenics legacy in educational activities.
- Investigate sustainable and inclusive teaching and learning approaches that continue to develop capacities of the UCL community to **understand **and **address** the legacies and ongoing consequences of eugenics thinking today.

ELEP is theoretically anchored within the field of difficult knowledge studies. Britzman (1998) developed the concept of ‘difficult knowledge’ to investigate the ways that experiences of education and learning can be problematic, uncomfortable, and even harmful when encountering complex curriculum areas. ELEP will support educational projects that encourage engagement with core issues in social justice-oriented approaches to education, such as difficult knowledge (Britzman, 1998), affective solidarity (Hemmings, 2012), counter storytelling (Bell, 1987), education and harm (Love, 2019), inclusive education (Morina, 2017), implication (Rothberg, 2019), and productive pedagogies (Zembylas, 2022).

While there is more thinking to be done around these ideas, the concept of ‘difficult knowledge’ offers a productive starting point for thinking together about aspects of our education work that are difficult for us to do in our day-to-day work. This theorisation of the eugenics legacy also offers space for reflection within our UCL community around ideas about educational **implication and accountability**, necessary for addressing the harms caused by eugenics in the past. Eugenics is undoubtedly an example of a ‘difficult knowledge’ and through the development of staff learning opportunities, student engagement and resource development, ELEP will explore how UCL’s eugenics legacy can be positioned within educational activities in sustainable and meaningful
ways.

The ELEP team are keen to develop supportive and collegiate relationships so that the work taking place in the department can be amplified across UCL and can also be shared with other institutions doing the same work. We are interested in thinking about the tensions we encounter as educators when working with theories and ideas in our teaching developed by eugenicists. We think there is more work to do in thinking about the status of de-named buildings and rooms and how they can be repurposed educationally. ELEP will necessarily focus in on eugenics histories at UCL, but we also aim to prompt reflection on the broader implications for working with other types of problematic legacies within higher education institutions. We welcome feedback from all staff and students as part of our continuing dialogue with educators and in order to share our experiences of this important post inquiry work.

## References

Bell, D. (1987) And we are not saved: The elusive quest for racial justice. New York. Basic Books.

Britzman, D. P. 1998. Lost Subjects, Contested Objects: Toward a Psychoanalytic Inquiry of Learning. Albany, NY: SUNY Press.

Davies, L. (2017) Justice-sensitive education: the implications of transitional justice mechanisms for teaching and learning, Comparative Education, 53:3, 333-350, DOI: 10.1080/03050068.2017.1317999

Hemmings, C. (2012). Affective solidarity: Feminist reflexivity and political transformation. Feminist Theory, 13(2), 147–161. https://doi.org/10.1177/1464700112442643

Love, B. (2019) We want to do more than survive: Abolitionist Teaching and the Pursuit of Educational Freedom. Boston. Beacon Press.

Moriña, A. (2017) Inclusive education in higher education: challenges and opportunities, European Journal of Special Needs Education, 32:1, 3-17, DOI: 10.1080/08856257.2016.1254964

Rothberg, M. (2019) The implicated subject: beyond victims and perpetrators. Stanford. Stanford University Press.

Zembylas, M. (2022) Ethics, politics and affects: renewing the conceptual and pedagogical framework of addressing fanaticism in education. Ethics and Education 17:3, pages 261-276.

{{< include /posts/_info.qmd >}}

<br>

{{< include /posts/_share.qmd >}}

